name: Bowshot
version: '${project.version}'
main: bowshot.Bowshot
api-version: '26.1'
authors: [ Perdume ]
softdepend: [ FancyHolograms, PlaceholderAPI, Vault, WorldGuard, LuckPerms, Essentials ]

commands:
  bs:
    usage: "/bs <join|leave|spect|stats|replay>"
    description: Bowshot user command
    aliases: [ bowshot ]
  bsa:
    usage: "/bsa <help>"
    description: Bowshot admin command
    permission: bowshot.admin
    aliases: [ bowshotadmin ]

permissions:
  bowshot.admin:
    description: Access to admin commands
    default: op